//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NK_Back_end_API.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string position { get; set; }
        public string image_type { get; set; }
        public byte[] image { get; set; }
        public IRoleAccount role { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    }
}
